<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Autofac" />
    <PackageReference Include="Volo.Abp.EventBus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TrueParser.Abp.EventBus.Nats\TrueParser.Abp.EventBus.Nats.csproj" />
  </ItemGroup>

</Project>
